apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
     app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hudsonfranca/videosapp_frontend:latest
        resources:
          limits:
            cpu: "0.9"
            memory: "900Mi"
          requests:
            cpu: "0.6"
            memory: "600Mi"
        ports:
        - containerPort: 3000


